### ISSUE TITLE
Do you have a version for Cake PHP v2.x?

### ISSUE THREAD

**Issue by FrodeMMeling** [WyriHaximus/FlyPie#1]

**Comment by WyriHaximus** [comment]
There is no version for v2 and none planned. Mainly because it is a lot more complicated to setup composer  for v2 where v3 is build using it.

**Comment by FrodeMMeling** [comment]
Ok. Strange. I use composer with v2, I only add:

```
require APP . 'Vendor/autoload.php';
spl_autoload_unregister(array('App', 'load'));
spl_autoload_register(array('App', 'load'), true, true);
```
to bootstrap.php.
I have league/flysystem working, so not a big deal.

**Comment by WyriHaximus** [comment]
Added that to an app is simple but educating users is a lot harder in my experience. Another thing is that I moved away from v2 a while ago without looking back.
