### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by segy** [WyriHaximus/FlyPie#14]
Hi 

could you please make a release (I suggest v1.1.1)? The `@return` annotation on `FilesystemsTrait:: filesystem` was fixed in master, but not yet in 1.1.0 which breaks phpstan tests. 

Thanks

**Comment by WyriHaximus** [comment]
Sure, I'll tag it shortly :+1:

**Comment by segy** [comment]
thanks

**Comment by WyriHaximus** [comment]
Here you go: [`1.1.1`](https://github.com/WyriHaximus/FlyPie/releases/tag/1.1.1)
