### ISSUE TITLE
CakePHP 4 compatibility

### ISSUE THREAD

**Issue by swiffer** [WyriHaximus/FlyPie#18]
Ist a CakePHP 4 compatible Release coming Out/in the making?

**Comment by WyriHaximus** [comment]
Hey @swiffer, there are no real plans mainly because I'm not use CakePHP anymore. But since I'm also still maintaining https://github.com/WyriHaximus/TwigView because it's used by CakePHP's bake these days I'll also make sure this plugin gets bumped to CakePHP 4.

**Comment by swiffer** [comment]
Hi @WyriHaximus - just wanted to give a quick update. I'm running the latest master successfully in a CakePHP 4.0 based project. Some Tests are still failing but would be great to get these sorted out and a beta branch out soon. Thanks for your work!

**Comment by WyriHaximus** [comment]
Hey @swiffer been very busy, if you want to create a PR for that that would be very welcome. If not will probably pick this up half way into March

**Comment by swiffer** [comment]
Hi @WyriHaximus - found some time to fix broken travis pipeline by pinning the distro, bumping to supported php versions, etc. I've removed unmaintained dependecies (dunit) as well, migrated the helper scripts from makefile to composer (in cakephp fashion ;)), ... (see the changes in my pr for details).

there is currently one test failing as createMock is no longer public, i don't know exactly what we are testing here. can you please take a look?

I dropped support for CakePHP 3 as supporting both at the same time is harder to archive. most other plugins have released new major versions as well (authorization, authentication, search, duplicable, ...) so I hope you're fine doing this as well.

**Comment by swiffer** [comment]
fixed the testsuite. I think most of the .scruntizer.yml config is outdated & no longer working when looking to their docs. However I've close to 0 experience with their service, maybe you can take a look.

Configuration & Supported Analysis tools look quite different when looking at their current docs.

https://scrutinizer-ci.com/docs/tools/php/code-sniffer/

Can we remove most of the no longer relevant configuration entries and simplify that?

**Comment by swiffer** [comment]
After Reading the Docs, removed the legacy Tools section and migrated to the newer and Vetter scruntizer checks

**Comment by swiffer** [comment]
Can you Update the readme? Missed that one (maybe https://github.com/dereuromark/cakephp-ide-helper/blob/master/README.md is a good example for available Versions) and Release a Beta (e.g. 2.0.0-beta1) Afterwards? Thanks!

**Comment by swiffer** [comment]
@WyriHaximus - added additional changes. looking forward to 2.0.0-beta ;)

**Comment by WyriHaximus** [comment]
Will have a look at that tomorrow, thanks for the PR's 👍

**Comment by WyriHaximus** [comment]
There you go:  [`2.0.0-beta1`](https://github.com/WyriHaximus/FlyPie/releases/tag/2.0.0-beta1)
