### ISSUE TITLE
Throw Exeption for WebDAV-Adaptor if php-xml is missing

### ISSUE THREAD

**Issue by 3811015** [WyriHaximus/FlyPie#9]
Took me some time to get to the fault.

Simple missing packet killed a day. 
So maybe a short verification could help the next developer not to fall again over this...

**Comment by WyriHaximus** [comment]
Could you provide more details on how you discovered the need for `php-xml` and what exactly needed it?

**Comment by 3811015** [comment]
If you use FlyPie to implement the webDAV Flysystem Adaptor, which relies on the Sabre Client, you need it to parse the requests and responses.

**Comment by WyriHaximus** [comment]
Adding it here as specific requirement for WebDAV-Adapters in `composer.json` doesn't make sense, that has to be done on https://github.com/fruux/sabre-dav which already has ext-dom in the requirements which covers XML. So you either should have had an error about it already or you're probably not installing using composer.
